# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 10000

format = """
$username\
$hostname\
$localip\
$sh1v1\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$line_break\
$character\
"""

[directory]
truncation_length = 50

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_state]
style= "bright-black"

[git_status]
format = "[[(*$untracked$modified$renamed$deleted)](white)  ($conflicted )($staged )($ahead_behind )($stashed)]($style)"
style = "dimmed bright-black"
ahead = '[↑](dimmed white)${count}'
behind = '[↓](dimmed white)${count}'
diverged = '[⇅](dimmed white)${count}'
conflicted = "[✕](dimmed white)${count}"
untracked = "​"
modified = "​"
staged = "[+](dimmed white)${count}"
renamed = "​"
deleted = "​"
stashed = "[≡](dimmed white)${count}"
